Chapter18: Chapter18.o Chapter18_test.o
	cd ../DataStructure; make; cd ../Chapter18; g++ Chapter18 Chapter18.o Chapter18_test.o ../DataStructure/DataStructure.o;

Chapter18.o: Chapter18.h Chapter18.cc

Chapter18_test.o: Chapter18.h Chapter18_test.cc

.PHONY clean:
	rm Chapter17; rm *.o; cd ../DataStructure; make clean;


