

Chapter1: Chapter1.o Chapter1_test.o
	cd ../DataStructure; make; cd ../Chapter1; g++ -o Chapter1 Chapter1.o Chapter1_test.o ../DataStructure/DataStructure.o


Chapter1.o: Chapter1.h

Chapter1_test.o: Chapter1.h


.PHONY clean:
	rm *.o Chapter1; cd ../DataStructure; make clean;




